name: ATLA
favicon: null
layout_spectrum: 0.6559918343555182
typography_spectrum: 0.6144481333903968
title: An Atlantic Based Waterman Company
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.5502254019957036
  lightness: 0.5756913525983691
  saturation: 0.726569571532309
  rhythmicContrast: 0.08024899335578084
purpose: []
